apiVersion: apps/v1
kind: Deployment 
metadata:
  name: spring-petclinic
  namespace: dev
  labels:
    app: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers: 
      - name: spring-petclinic
        image: kub-ansible:5000/admin/spring-petclinic:latest
#        command: [ "bin/bash", "-c", "./wrapper.sh" ]
        ports:
        - containerPort: 8080
        
       
   
        
